%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam:1
event_txt: 0

imu_topic: "/DAVIS346_left/imu"
image0_topic: "/DAVIS346_left/image"
event_topic: "/DAVIS346_left/events"
event_txt_path: "none"
image1_topic: "/DAVIS346_right/image"
output_path: "/home/hjf/.ros/EE-VINS"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 346
image_height: 260
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   # data: [1, 0, 0, 0,
   #        0, 1, 0, 0,
   #        0, 0, 1, 0,
   #        0, 0, 0, 1]
   data: [-0.999753379925201, -0.001757275388879, 0.022138006038118, 0.304682038097617,
          -0.001514856391958, 0.999938763967426, 0.010962368603895, 0.431448063933834,
          -0.022155914295011, 0.010926129163778, -0.999694821014518, -1.32969989922647,
          0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0, 0.0, 1.0, 0.0,
          1.0, 0.0, 0.0, 0.05,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

#Multiple thread support
multiple_thread: 1

test: 0.3

#feature traker paprameters
max_cnt: 600           # max feature number in feature tracking
min_dist: 10            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
max_depth: 500.0         # max estimated depth (m) 注释了
show_track: 1
show_image_feat_weight: 1
# publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#EE-VINS parameters
dyna_on:   true # do not change it to false
regularization_lambda:  5.0
momentum_on:      true
momentum_lambda:   1.0
alternating_converge:   0.9
margin_feature_thresh:  0.1


#optimization parameters
max_solver_time: 0.5  # max solver itration time (ms), to guarantee real time
max_num_iterations: 15   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.04          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.004         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.0004         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.80766     # gravity magnitude

#unsynchronization parameters
estimate_td: 0.2142190854473522                     # online estimate time offset between camera and imu
td: 0.0                              # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
